"""empty message

Revision ID: 050e2c5831c9
Revises: 
Create Date: 2022-02-08 16:19:01.804170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050e2c5831c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_notion_pages',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('last_edited_time', sa.DateTime(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('bookmarks_for_remove',
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.Column('primary_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('primary_id'),
    sa.UniqueConstraint('bookmark_id')
    )
    op.create_table('new_pages',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('last_edited_time', sa.DateTime(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('page_id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_pages')
    op.drop_table('bookmarks_for_remove')
    op.drop_table('all_notion_pages')
    # ### end Alembic commands ###
